version: '2.1'
services:
  db:
    build:
      context: ./Docker/MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    container_name: gorest_db
    ports:
      - "3306:3306"
    tty: true
  app:
    build:
      context: ./
    volumes:
      - ./:/go/src/github.com/dogukanayd/go-rest
    container_name: gorest_app
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db