[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.4.0"

[[constraint]]
  name = "upper.io/db.v3"
  version = "3.6.3"

[[constraint]]
    name = "github.com/go-redis/redis"
    version = "6.15.5"